name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Deployment environment"
        options:
          - staging
          - production
      version:
        description: "Version to deploy"
        required: true
      notify-team:
        type: boolean
        default: false
      push-to-docker-hub:
        type: boolean
        default: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run format:check

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm audit --audit-level=high

  test:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [lint, format-check, security-audit]
    strategy:
      matrix:
        node: [16, 18, 20]
    container:
      image: node:${{ matrix.node }}
      options: --cpus 2 --memory 4g
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-
      - run: npm ci
      - run: npm test -- --coverage --reporters=default --reporters=jest-junit
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Archive test reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-report-node-${{ matrix.node }}
          path: junit.xml
      - name: Archive coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.node }}
          path: coverage/

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: app_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: docker compose up -d
      - run: curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
      - run: chmod +x wait-for-it.sh
      - run: ./wait-for-it.sh localhost:5432 --timeout=30 --strict
      - run: npm run integration-test

  build:
    runs-on: ubuntu-latest
    needs: integration-test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  docker-push:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.inputs.push-to-docker-hub == 'true'  && github.ref == 'refs/heads/main'}}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/lab-14-tdo:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/lab-14-tdo:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/lab-14-tdo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/lab-14-tdo:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/lab-14-tdo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy App
        uses: ./.github/actions/custom-deploy
        with:
          environment: ${{ github.event.inputs.environment }}
          version: ${{ github.event.inputs.version }}
          notify-team: ${{ github.event.inputs.notify-team }}

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ github.event.inputs.notify-team == 'true' }}
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueTitle = `[CI/CD] Deployment ${process.env.ENVIRONMENT || 'N/A'} finished: ${process.env.STATUS}`;
            const issueBody = `
              **Deployment Result**
              - Environment: ${process.env.ENVIRONMENT || 'N/A'}
              - Version: ${process.env.VERSION || 'N/A'}
              - Status: ${process.env.STATUS}
              - Run URL: [Run logs](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID})
              This issue was created automatically by GitHub Actions.
            `;
            const labels = ['ci-cd', 'automated'];

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: labels
            });
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          VERSION: ${{ github.event.inputs.version }}
          STATUS: ${{ job.status }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}

permissions:
  contents: read
  issues: write
